version: "3.8"
services:
  db:
    image: postgres:14  # PostgreSQLのサービスを指定
    environment:
      POSTGRES_USER: aoi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aoi_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    environment:
      - PORT=80  # Renderで使用するポートを80に変更
    volumes:
      - ".:/myapp"
    ports:
      - "80:3000"  # ポート80をホストにバインドし、コンテナ内の3000ポートにマッピング
    depends_on:
      - db

volumes:
  postgres_data:
